#cloud-config
timezone: Asia/Tokyo

apt:
  sources:
    docker.list:
      source: deb [arch=arm64 signed-by=$KEY_FILE] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - make
  - docker-ce
  - docker-ce-cli
  - docker-compose

system_info:
  default_user:
    groups: [docker]
